# Generated by Django 4.2.7 on 2025-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=150, verbose_name='Họ tên')),
                ('PhoneNumber', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('JobTitle', models.CharField(help_text='VD: Pha chế, Thu ngân, Quản lý', max_length=100, verbose_name='Chức vụ')),
                ('WorkShift', models.CharField(choices=[('SANG', 'Ca sáng'), ('CHIEU', 'Ca chiều'), ('TOI', 'Ca tối'), ('FULL', 'Full time')], default='FULL', max_length=50, verbose_name='Ca làm việc')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'NhanVien',
                'ordering': ['FullName'],
                'indexes': [models.Index(fields=['PhoneNumber'], name='NhanVien_PhoneNu_336584_idx'), models.Index(fields=['WorkShift'], name='NhanVien_WorkShi_97ca94_idx')],
            },
        ),
    ]
