# Generated by Django 4.2.7 on 2025-09-29 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=150, verbose_name='Họ tên')),
                ('PhoneNumber', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('Email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('RegisterDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng ký')),
                ('LoyaltyPoints', models.IntegerField(default=0, verbose_name='Điểm thành viên')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'db_table': 'KhachHang',
                'ordering': ['-RegisterDate'],
                'indexes': [models.Index(fields=['PhoneNumber'], name='KhachHang_PhoneNu_129f08_idx'), models.Index(fields=['Email'], name='KhachHang_Email_33519e_idx')],
            },
        ),
    ]
