# Generated by Django 4.2.7 on 2025-11-26 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0002_nguyenlieu_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('ImportID', models.AutoField(primary_key=True, serialize=False)),
                ('ImportDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'db_table': 'PhieuNhapKho',
                'ordering': ['-ImportDate'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Số lượng')),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá')),
                ('ImportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.phieunhapkho', verbose_name='Phiếu nhập kho')),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.nguyenlieu', verbose_name='Nguyên liệu')),
            ],
            options={
                'verbose_name': 'Chi tiết nhập kho',
                'verbose_name_plural': 'Chi tiết nhập kho',
                'db_table': 'ChiTietNhapKho',
            },
        ),
        migrations.AddIndex(
            model_name='phieunhapkho',
            index=models.Index(fields=['ImportDate'], name='PhieuNhapKh_ImportD_ea08cb_idx'),
        ),
        migrations.AddIndex(
            model_name='phieunhapkho',
            index=models.Index(fields=['EmployeeID'], name='PhieuNhapKh_Employe_1bbf46_idx'),
        ),
        migrations.AddIndex(
            model_name='chitietnhapkho',
            index=models.Index(fields=['ImportID'], name='ChiTietNhap_ImportI_6d03e4_idx'),
        ),
        migrations.AddIndex(
            model_name='chitietnhapkho',
            index=models.Index(fields=['IngredientID'], name='ChiTietNhap_Ingredi_9e9607_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chitietnhapkho',
            unique_together={('ImportID', 'IngredientID')},
        ),
    ]
