# Generated by Django 4.2.7 on 2025-09-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongThuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Số lượng')),
                ('Unit', models.CharField(max_length=20, verbose_name='Đơn vị')),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.nguyenlieu', verbose_name='Nguyên liệu')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Công thức',
                'verbose_name_plural': 'Công thức',
                'db_table': 'CongThuc',
                'indexes': [models.Index(fields=['ProductID'], name='CongThuc_Product_0adc64_idx'), models.Index(fields=['IngredientID'], name='CongThuc_Ingredi_8333f9_idx')],
                'unique_together': {('ProductID', 'IngredientID')},
            },
        ),
    ]
