# Generated by Django 4.2.7 on 2025-11-26 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_detail', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('avatar', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ảnh đại diện')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('citizen_id', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='CCCD/CMND')),
                ('gender', models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], default='OTHER', max_length=10, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Người liên hệ khẩn cấp')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT người liên hệ khẩn cấp')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mối quan hệ')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Ngày vào làm')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phòng ban')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Lương cơ bản')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Chi tiết nhân viên',
                'verbose_name_plural': 'Chi tiết nhân viên',
                'db_table': 'employee_details',
            },
        ),
    ]
