# Generated by Django 4.2.7 on 2025-11-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='position',
        ),
    ]
