# Generated by Django 4.2.7 on 2025-11-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_employeedetail_department_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeedetail',
            index=models.Index(fields=['hire_date'], name='employee_de_hire_da_556496_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedetail',
            index=models.Index(fields=['salary'], name='employee_de_salary_61b8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedetail',
            index=models.Index(fields=['phone_number'], name='employee_de_phone_n_16e7bd_idx'),
        ),
    ]
