# Generated by Django 4.2.7 on 2025-09-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá')),
                ('ImageUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hình ảnh')),
                ('Status', models.IntegerField(choices=[(0, 'Hết hàng'), (1, 'Còn hàng'), (2, 'Ngừng kinh doanh')], default=1, verbose_name='Trạng thái')),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.danhmucsanpham', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'SanPham',
                'ordering': ['ProductName'],
                'indexes': [models.Index(fields=['CategoryID'], name='SanPham_Categor_041c35_idx'), models.Index(fields=['Status'], name='SanPham_Status_42452c_idx')],
            },
        ),
    ]
