# Generated by Django 4.2.7 on 2025-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguyenLieu',
            fields=[
                ('IngredientID', models.AutoField(primary_key=True, serialize=False)),
                ('IngredientName', models.CharField(max_length=200, verbose_name='Tên nguyên liệu')),
                ('QuantityInStock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Số lượng tồn kho')),
                ('MinQuantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Số lượng tối thiểu')),
            ],
            options={
                'verbose_name': 'Nguyên liệu',
                'verbose_name_plural': 'Nguyên liệu',
                'db_table': 'NguyenLieu',
                'ordering': ['IngredientName'],
            },
        ),
    ]
