# Generated by Django 4.2.7 on 2025-10-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguyenlieu',
            name='Unit',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Đơn vị'),
        ),
    ]
