# Generated by Django 4.2.7 on 2025-11-27 02:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='Ngày làm việc')),
                ('shift_start_time', models.TimeField(verbose_name='Giờ bắt đầu ca')),
                ('shift_end_time', models.TimeField(verbose_name='Giờ kết thúc ca')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Lịch làm việc',
                'verbose_name_plural': 'Lịch làm việc',
                'db_table': 'work_schedules',
                'ordering': ['-schedule_date', 'shift_start_time'],
                'indexes': [models.Index(fields=['employee', 'schedule_date'], name='work_schedu_employe_96c1c1_idx'), models.Index(fields=['schedule_date'], name='work_schedu_schedul_31fd19_idx'), models.Index(fields=['is_active'], name='work_schedu_is_acti_f7c18d_idx')],
                'unique_together': {('employee', 'schedule_date', 'shift_start_time')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('work_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='1 giờ = 1 công, tối đa 16 công/ngày', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('16.00'))], verbose_name='Số công (giờ)')),
                ('status', models.CharField(choices=[('PRESENT', 'Có mặt'), ('ABSENT', 'Vắng mặt'), ('LATE', 'Đi muộn'), ('EARLY_LEAVE', 'Về sớm'), ('OVERTIME', 'Tăng ca'), ('LEAVE', 'Nghỉ phép'), ('SICK_LEAVE', 'Nghỉ ốm')], default='PRESENT', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bản ghi chấm công',
                'verbose_name_plural': 'Bản ghi chấm công',
                'db_table': 'attendance_records',
                'ordering': ['-date', '-check_in_time'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_6b3da7_idx'), models.Index(fields=['date'], name='attendance__date_19baa0_idx'), models.Index(fields=['status'], name='attendance__status_5b1243_idx'), models.Index(fields=['employee', '-date'], name='attendance__employe_e50692_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
