# Generated by Django 4.2.7 on 2025-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='idx_emp_date',
            old_name='attendance__employe_6b3da7_idx',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Ngày'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Có mặt'), ('ABSENT', 'Vắng mặt'), ('LATE', 'Đi muộn'), ('EARLY_LEAVE', 'Về sớm'), ('OVERTIME', 'Tăng ca'), ('LEAVE', 'Nghỉ phép'), ('SICK_LEAVE', 'Nghỉ ốm')], db_index=True, default='PRESENT', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='idx_date_status'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date', 'status'], name='idx_emp_date_status'),
        ),
    ]
