# Generated by Django 4.2.7 on 2025-11-26 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đặt')),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('Discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('FinalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Thành tiền')),
                ('PaymentMethod', models.CharField(choices=[('CASH', 'Tiền mặt'), ('CARD', 'Thẻ'), ('MOMO', 'MoMo'), ('BANKING', 'Chuyển khoản')], default='CASH', max_length=50, verbose_name='Phương thức thanh toán')),
                ('Status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('PREPARING', 'Đang chuẩn bị'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=50, verbose_name='Trạng thái')),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.khachhang', verbose_name='Khách hàng')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'db_table': 'HoaDon',
                'ordering': ['-OrderDate'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('OrderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(verbose_name='Số lượng')),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá')),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Thành tiền')),
                ('ToppingNote', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú topping')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.hoadon', verbose_name='Hóa đơn')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'db_table': 'ChiTietDonHang',
            },
        ),
        migrations.AddIndex(
            model_name='hoadon',
            index=models.Index(fields=['OrderDate'], name='HoaDon_OrderDa_864125_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadon',
            index=models.Index(fields=['Status'], name='HoaDon_Status_590169_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadon',
            index=models.Index(fields=['CustomerID'], name='HoaDon_Custome_8d4a54_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadon',
            index=models.Index(fields=['EmployeeID'], name='HoaDon_Employe_db4fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='chitietdonhang',
            index=models.Index(fields=['OrderID'], name='ChiTietDonH_OrderID_53e594_idx'),
        ),
        migrations.AddIndex(
            model_name='chitietdonhang',
            index=models.Index(fields=['ProductID'], name='ChiTietDonH_Product_b0cce3_idx'),
        ),
    ]
