# Generated by Django 4.2.7 on 2025-12-11 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hoadon',
            name='HoaDon_OrderDa_864125_idx',
        ),
        migrations.RemoveIndex(
            model_name='hoadon',
            name='HoaDon_Status_590169_idx',
        ),
        migrations.RemoveIndex(
            model_name='hoadon',
            name='HoaDon_Custome_8d4a54_idx',
        ),
        migrations.RemoveIndex(
            model_name='hoadon',
            name='HoaDon_Employe_db4fc1_idx',
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='OrderDate',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ngày đặt'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='PaymentMethod',
            field=models.CharField(choices=[('CASH', 'Tiền mặt'), ('CARD', 'Thẻ'), ('MOMO', 'MoMo'), ('BANKING', 'Chuyển khoản')], db_index=True, default='CASH', max_length=50, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('PREPARING', 'Đang chuẩn bị'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], db_index=True, default='PENDING', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AddIndex(
            model_name='hoadon',
            index=models.Index(fields=['OrderDate', 'Status'], name='idx_order_date_status'),
        ),
        migrations.AddIndex(
            model_name='hoadon',
            index=models.Index(fields=['Status', 'OrderDate'], name='idx_status_date'),
        ),
        migrations.AddIndex(
            model_name='hoadon',
            index=models.Index(fields=['CustomerID', 'OrderDate'], name='idx_customer_date'),
        ),
        migrations.AddIndex(
            model_name='hoadon',
            index=models.Index(fields=['EmployeeID', 'OrderDate'], name='idx_employee_date'),
        ),
        migrations.AddIndex(
            model_name='hoadon',
            index=models.Index(fields=['PaymentMethod'], name='idx_payment_method'),
        ),
    ]
